### ISSUE TITLE
Ejercicio 7 y ejercicio 10

### ISSUE THREAD

**Issue by chiarab22** [chiarab22/LasTablas#2]
@Patriesc : 
- En el ejercicio 7 solo consigo generar un carácter aleatorio en vez de varios
- En el ejercicio 10 no consigo imprimir la información al buscar un empleado

**Comment by Patriesc** [comment]
Ya he solucionado el problema con el ejercicio 7, tenías que cambiar el valor por cada iteración del bucle.
Voy a revisar ahora el ejercicio 10

**Comment by Patriesc** [comment]
Ya he corregido el ejercicio 10, he creado una nueva clase Empleado para una mejor estructuración.
Es posible que me haya complicado más de la cuenta en el ejercicio, por si quieres simplificarlo.
